# Generated by Django 4.2.1 on 2023-07-06 16:38

import app_login.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', app_login.models.UserManager()),
            ],
        ),
    ]
